; PlatformIO Project Configuration File
; ... resto igual ...
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    # Librería para la comunicación MQTT
    knolleary/PubSubClient @ ^2.8
    # Librería para parsear los datos del GPS de forma sencilla
    mikalhart/TinyGPSPlus @ ^1.0.3
    # Librería para el expansor de pines I2C (corregida)
    xreef/PCF8574 @ ^1.3.1
